In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns

In [2]:
df=pd.read_csv('emails.csv')

In [3]:
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5728 rows x 2 columns]

In [7]:
df['spam'].value_counts()

spam
0    4327
1    1368
Name: count, dtype: int64

In [11]:
df.drop_duplicates(inplace=True)

In [12]:
df['spam'].value_counts()

spam
0    4327
1    1368
Name: count, dtype: int64

In [9]:
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5695 rows x 2 columns]

In [13]:
df['spam'].value_counts()

spam
0    4327
1    1368
Name: count, dtype: int64

In [6]:
df.isnull().sum()

text    0
spam    0
dtype: int64

# **separate x and y**

In [14]:
x=df.text.values

In [15]:
y=df.spam.values

In [16]:
x

array(["Subject: naturally irresistible your corporate identity  lt is really hard to recollect a company : the  market is full of suqgestions and the information isoverwhelminq ; but a good  catchy logo , stylish statlonery and outstanding website  will make the task much easier .  we do not promise that havinq ordered a iogo your  company will automaticaily become a world ieader : it isguite ciear that  without good products , effective business organization and practicable aim it  will be hotat nowadays market ; but we do promise that your marketing efforts  will become much more effective . here is the list of clear  benefits : creativeness : hand - made , original logos , specially done  to reflect your distinctive company image . convenience : logo and stationery  are provided in all formats ; easy - to - use content management system letsyou  change your website content and even its structure . promptness : you  will see logo drafts within three business days . affordability : y

In [17]:
y

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

# **split dataset**

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
xtrain, xtest, ytrain, ytest=train_test_split(x,y,test_size=0.2)

# **Data Preprocessing**

In [20]:
from sklearn.feature_extraction.text import CountVectorizer

In [21]:
cv=CountVectorizer()
x_train=cv.fit_transform(xtrain)

In [22]:
x_train

<4556x33746 sparse matrix of type '<class 'numpy.int64'>'
	with 560918 stored elements in Compressed Sparse Row format>

In [23]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

# **ML Algorithm**

In [24]:
from sklearn.naive_bayes import MultinomialNB

In [26]:
model=MultinomialNB() 
model.fit(x_train,ytrain)

MultinomialNB()

In [27]:
x_test=cv.transform(xtest)

In [28]:
x_test

<1139x33746 sparse matrix of type '<class 'numpy.int64'>'
	with 139856 stored elements in Compressed Sparse Row format>

In [29]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [30]:
model.score(x_test,ytest)

0.9912203687445127

In [31]:
emails=['hey i am looking for machine learning tutorial in bengali language','hey you win an iphone x giveway for free please do the survey']

In [32]:
cv_emails=cv.transform(emails)

In [33]:
model.predict(cv_emails)

array([0, 1], dtype=int64)